# Generated by Django 4.2.4 on 2023-08-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=100, verbose_name='Employee Type')),
            ],
            options={
                'verbose_name': 'EmployeeType',
                'verbose_name_plural': 'EmployeesTypes',
                'db_table': 'EmployeeType',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='erp.employeetype'),
            preserve_default=False,
        ),
    ]
