# Generated by Django 4.2.4 on 2023-08-16 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=80, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=80, verbose_name='Last Name')),
                ('dni', models.CharField(max_length=15, verbose_name='DNI')),
                ('gender', models.CharField(max_length=1)),
                ('birthdayDate', models.DateField()),
                ('address', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'DetailProductSale',
                'verbose_name_plural': 'DetailProductsSales',
                'db_table': 'DetailProductSale',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.client')),
                ('detailProductSale', models.ManyToManyField(blank=True, through='erp.DetailProductSale', to='erp.product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sale',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='detailproductsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.product'),
        ),
        migrations.AddField(
            model_name='detailproductsale',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.sale'),
        ),
    ]
