print('Operadores Aritmenticos'.upper())
print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print(3 % 2)
print(10 // 3)
print(2 ** 3)

print('Operadores Comparacion 1'.upper()) 
print(3 > 4)
print(3 < 4)
print(3 >= 4)
print(3 <= 4)
print(3 == 4)
print(3 != 4)

print('Operadores Comparacion 2'.upper())
print(3 > 4 and "Hola" > "Python")
print(3 > 4 or "Hola" > "Python")
print(3 < 4 and "Hola" < "Python")
print(3 < 4 or "Hola" < "Python")
print(not(3 > 4))