# Generated by Django 4.1.3 on 2022-11-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('webSite', models.URLField(max_length=100)),
                ('fundation', models.PositiveIntegerField()),
            ],
        ),
    ]
